include:
  - baseline.banner
  - baseline.freeipa
  - baseline.netbird
  - baseline.profile
  - baseline.schedule
  - baseline.systemd-resolved
  - baseline.timesyncd
  - baseline.trivy
  - baseline.updates
  - baseline.usb
